### ISSUE TITLE
Help menu buttons don't work

### ISSUE THREAD

**Issue by JohannesBuchner** [lucaskorol21/GO-RXR#43]
License:
```
Traceback (most recent call last):
  File "/mnt/data/daten/PostDoc2/home/Downloads/GO-RXR/GUI_GO.py", line 9256, in _license
    license = licenseWidget()
              ^^^^^^^^^^^^^^^
  File "/mnt/data/daten/PostDoc2/home/Downloads/GO-RXR/GUI_GO.py", line 11487, in __init__
    with open('license.txt', 'r',encoding='ISO-8859-1') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'license.txt'
```
About:
`gio: file:GO-RXR_UserGuide_v0.3.1.pdf: Operation not supported`

Tips:
```
Traceback (most recent call last):
  File "/mnt/data/daten/PostDoc2/home/Downloads/GO-RXR/GUI_GO.py", line 9264, in _tips
    license = tipsWidget()
              ^^^^^^^^^^^^
  File "/mnt/data/daten/PostDoc2/home/Downloads/GO-RXR/GUI_GO.py", line 11519, in __init__
    with open('tips.txt', 'r',encoding='ISO-8859-1') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'tips.txt'

```

**Comment by jpcurbelo** [comment]
We just updated the Help Menu. Now the options listed are:
- User Guide (loads the pdf file with the documentation)
- Tips (load a list of useful tips)
- License (loads the updated license file - we included legal names here)

**Comment by jpcurbelo** [comment]
Please, let me know if we can close this issue.

**Comment by JohannesBuchner** [comment]
Can you confirm that you tested, by clicking at each, and that works for you?

**Comment by jpcurbelo** [comment]
Hi, @JohannesBuchner. Yes, I can confirm that I have tested and the three options are working as expected. Please, take a look at the screencast and let us know whether you are facing any issues on your end. Tahnks.
[go-rxr_help_menu.webm](https://github.com/user-attachments/assets/2974f11f-cf9a-4d39-871d-6e1a904c50b2)

**Comment by JohannesBuchner** [comment]
Works for me with latest version
